frontend:
  - changed-files:
      - any-glob-to-any-file: 'src/**'

docs:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

config:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'tsconfig*.json'
      - any-glob-to-any-file: 'vite.config.ts'
      - any-glob-to-any-file: 'eslint.config.js'
      - any-glob-to-any-file: '.prettierrc'
