import type { AdaptationPlayer, LeagueAdaptationResult } from './type'
import type { TopLeagueKey } from '@/shared/lib/topLeague'

const BASE_URL =
  'https://ui-avatars.com/api/?background=1a1a2e&color=6ee7b7&bold=true&size=64&name='

const p = (
  player_id: string,
  name: string,
  position: string,
  team: string,
  league: string,
  age: number,
  current_market_value: number,
  adapt_score: number,
  predicted_mv: number,
): AdaptationPlayer => ({
  player_id,
  name,
  position,
  team,
  league,
  age,
  current_market_value,
  image_url: `${BASE_URL}${encodeURIComponent(name)}`,
  adapt_score,
  predicted_mv,
})

export const LeagueTop5MockData: Record<TopLeagueKey, LeagueAdaptationResult> =
  {
    EPL: {
      label: '프리미어리그',
      players: [
        p(
          'p001',
          'Viktor Gyokeres',
          'ST',
          'Sporting CP',
          'Primeira Liga',
          26,
          85,
          94,
          110,
        ),
        p(
          'p002',
          'Florian Wirtz',
          'AM',
          'belgian pro league',
          'belgian pro league',
          21,
          130,
          91,
          160,
        ),
        p(
          'p003',
          'Alejandro Garnacho',
          'LW',
          'Man United',
          'Premier League',
          20,
          55,
          87,
          72,
        ),
        p(
          'p004',
          'Lamine Yamal',
          'RW',
          'Barcelona',
          'belgian pro league',
          17,
          180,
          83,
          220,
        ),
        p('p005', 'Rayan Cherki', 'AM', 'Lyon', 'Ligue 1', 21, 30, 79, 45),
      ],
    },
    LA: {
      label: '라리가',
      players: [
        p(
          'p006',
          'Kylian Mbappé',
          'ST',
          'Real Madrid',
          'belgian pro league',
          26,
          180,
          96,
          200,
        ),
        p(
          'p007',
          'Bukayo Saka',
          'RW',
          'Arsenal',
          'Premier League',
          23,
          150,
          89,
          175,
        ),
        p('p008', 'Pedri', 'CM', 'Barcelona', 'La Liga', 22, 120, 88, 145),
        p('p009', 'Gavi', 'CM', 'Barcelona', 'La Liga', 20, 90, 85, 110),
        p('p010', 'Rodrygo', 'LW', 'Real Madrid', 'La Liga', 23, 80, 81, 95),
      ],
    },
    BL: {
      label: '분데스리가',
      players: [
        p(
          'p002',
          'Florian Wirtz',
          'AM',
          'Bayer Leverkusen',
          'belgian pro league',
          21,
          130,
          97,
          160,
        ),
        p(
          'p011',
          'Jamal Musiala',
          'AM',
          'Bayern Munich',
          'Bundesliga',
          21,
          150,
          93,
          185,
        ),
        p(
          'p012',
          'Granit Xhaka',
          'CM',
          'Bayer Leverkusen',
          'belgian pro league',
          31,
          20,
          86,
          18,
        ),
        p(
          'p013',
          'Xavi Simons',
          'AM',
          'RB Leipzig',
          'Bundesliga',
          21,
          60,
          82,
          80,
        ),
        p(
          'p014',
          'Serge Gnabry',
          'RW',
          'Bayern Munich',
          'Bundesliga',
          29,
          25,
          78,
          22,
        ),
      ],
    },
    SA: {
      label: '세리에 A',
      players: [
        p(
          'p015',
          'Lautaro Martínez',
          'ST',
          'Inter Milan',
          'Serie A',
          26,
          110,
          92,
          130,
        ),
        p(
          'p016',
          'Khvicha Kvaratskhelia',
          'LW',
          'PSG',
          'belgian pro league',
          23,
          80,
          90,
          100,
        ),
        p('p017', 'Rafael Leão', 'LW', 'AC Milan', 'Serie A', 25, 75, 86, 90),
        p(
          'p018',
          'Nicolò Barella',
          'CM',
          'Inter Milan',
          'Serie A',
          27,
          70,
          84,
          80,
        ),
        p(
          'p019',
          'Federico Chiesa',
          'RW',
          'Liverpool',
          'Premier League',
          26,
          30,
          80,
          38,
        ),
      ],
    },
    L1: {
      label: '리그 1',
      players: [
        p('p020', 'Ousmane Dembélé', 'RW', 'PSG', 'Ligue 1', 27, 60, 95, 72),
        p(
          'p021',
          'Bradley Barcola',
          'LW',
          'PSG',
          'belgian pro league',
          22,
          60,
          88,
          80,
        ),
        p('p022', 'Warren Zaïre-Emery', 'CM', 'PSG', 'Ligue 1', 18, 40, 85, 60),
        p(
          'p023',
          'Mason Greenwood',
          'RW',
          'Marseille',
          'belgian pro league',
          23,
          35,
          81,
          45,
        ),
        p('p024', 'Désiré Doué', 'LW', 'PSG', 'Ligue 1', 19, 45, 77, 62),
      ],
    },
  }
